spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_lin?useUnicode=true&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
server:
  port: 8081
