spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_lin?useUnicode=true&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  security:
    user:
      name: lin
      password: 123456
      roles: USER,ADMIN
server:
  port: 8088
